### ISSUE TITLE
Faucet backend with recaptcha support

### ISSUE THREAD

**Issue by bette7** [cennznet/faucet-ui#1]
PROD faucet using Rimu and require recaptcha
UAT faucet using Rimu and don't require recaptcha but VPN protected
Deploy faucet UI to PROD that uses PROD faucet backend
Open PROD backend to public usage
Reduce given out token amount to 0.2
Ensure secrets are managed by k8s secrets

**Comment by ianhe8x** [comment]
published as github page: https://cennznet.js.org/faucet-ui/
